server:
  port: 8080

app:
  version: @maven.build.timestamp@
  build-timestamp: @maven.build.timestamp@
  mqtt:
    enabled: true
    host: localhost
    port: 1883
    username: ""
    password: ""
    tls: false
    clientId: ""

spring:
